<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="ReferencedAssemblies\MelonLoader.dll" />
    <Reference Include="ReferencedAssemblies\UnityEngine.CoreModule.dll" />
    <Reference Include="ReferencedAssemblies\UnityEngine.AssetBundleModule.dll" />
    <Reference Include="ReferencedAssemblies\Core.dll" />
    <Reference Include="ReferencedAssemblies\UI.dll" />
	<Reference Include="ReferencedAssemblies\Unity.InputSystem.dll" />
	<Reference Include="ReferencedAssemblies\UI.Interface.dll" />
    <Reference Include="ReferencedAssemblies\Ship.dll" />
    <Reference Include="ReferencedAssemblies\Ship.Interface.dll" />
    <Reference Include="ReferencedAssemblies\Items.Interface.dll" />
    <Reference Include="ReferencedAssemblies\Managers.Interface.dll" />
  </ItemGroup>
  
</Project>
